### ISSUE TITLE
Trained weights for test

### ISSUE THREAD

**Issue by hjinnkim** [yingutk/NL-MAT#1]
Thank you for your interesting and great research. I want to run your  code for the test. Can you share your trained weights?

**Comment by yingutk** [comment]
Hi, Thanks for your interest in our work. Please provide an image pair and run the code directly for testing. The weights are updated based on each image pair, so different image pairs will have different weights. The results are located in the folders: [data1_our_results_NL-MAT] and [data2_our_results_NL-MAT].

**Comment by hjinnkim** [comment]
Thank you for your kind reply! I may misunderstand some parts of your paper. I will re-read the paper and follow your instruction for test.
